from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='RiskConfig',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(default='primary',max_length=32,unique=True)),('default_symbol',models.CharField(default='1HZ100V',max_length=32)),('history_ticks',models.PositiveIntegerField(default=5000)),('stake_usd',models.FloatField(default=1.0)),('min_research_ticks',models.PositiveIntegerField(default=5000)),('min_demo_ticks',models.PositiveIntegerField(default=10000)),('min_edge_pp',models.FloatField(default=0.75)),('min_confidence_margin_pp',models.FloatField(default=0.0)),('max_daily_loss_usd',models.FloatField(default=10.0)),('max_consecutive_losses',models.PositiveIntegerField(default=5)),('max_demo_trades_per_day',models.PositiveIntegerField(default=20)),('demo_execution_enabled',models.BooleanField(default=False)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='DigitAggregate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('symbol',models.CharField(max_length=32,unique=True)),('pip_size',models.PositiveSmallIntegerField(default=2)),('total_ticks',models.BigIntegerField(default=0)),('digit_counts',models.JSONField(default=dict)),('transition_counts',models.JSONField(default=dict)),('last_digit',models.PositiveSmallIntegerField(blank=True,null=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='ResearchRun',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('symbol',models.CharField(max_length=32)),('contract_type',models.CharField(max_length=24)),('barrier',models.CharField(blank=True,max_length=8)),('ticks',models.PositiveIntegerField(default=0)),('assumed_return_pct',models.FloatField(default=0)),('trades',models.PositiveIntegerField(default=0)),('win_rate_pct',models.FloatField(default=0)),('net_units',models.FloatField(default=0)),('expectancy_units',models.FloatField(default=0)),('results',models.JSONField(default=dict)),('created_at',models.DateTimeField(auto_now_add=True))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='ProposalSnapshot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('symbol',models.CharField(max_length=32)),('contract_type',models.CharField(max_length=24)),('barrier',models.CharField(blank=True,max_length=8)),('stake',models.FloatField(default=1)),('ask_price',models.FloatField()),('payout',models.FloatField()),('break_even_pct',models.FloatField()),('model_probability_pct',models.FloatField(default=0)),('lower95_pct',models.FloatField(default=0)),('edge_pp',models.FloatField(default=0)),('sample_ticks',models.PositiveIntegerField(default=0)),('decision',models.CharField(default='NO TRADE',max_length=24)),('observed_at',models.DateTimeField(auto_now_add=True))],options={'ordering':['-observed_at']}),
        migrations.CreateModel(name='DemoTrade',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('symbol',models.CharField(max_length=32)),('contract_type',models.CharField(max_length=24)),('barrier',models.CharField(blank=True,max_length=8)),('stake',models.FloatField(default=1)),('proposal_id',models.CharField(blank=True,max_length=128)),('contract_id',models.CharField(blank=True,max_length=128)),('status',models.CharField(default='blocked',max_length=24)),('pnl',models.FloatField(blank=True,null=True)),('reason',models.TextField(blank=True)),('metadata',models.JSONField(default=dict)),('opened_at',models.DateTimeField(auto_now_add=True)),('closed_at',models.DateTimeField(blank=True,null=True))],options={'ordering':['-opened_at']})
    ]
